#!/usr/bin/env python3
"""Render INDEX.md and index.json from the lockfiles and the published releases.

The lockfiles say what should exist; the releases say what does. The index shows
both, so a system that is selected but not yet built is visible as pending rather
than silently absent.

Usage:
    render_index.py --repo owner/name [--out INDEX.md] [--json index.json]
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from archive_common import (
    LANGUAGES,
    REPO_ROOT,
    GitHub,
    load_policy,
    lockfile_path,
    read_lockfile,
    release_tag,
)

MAX_RELEASE_PAGES = 100


def human_bytes(n: int) -> str:
    if not n:
        return "—"
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024 or unit == "TB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} TB"


def collect_releases(gh: GitHub, repo: str) -> dict[str, dict]:
    """Map release tag -> {url, asset bytes} for releases carrying an archive."""
    found: dict[str, dict] = {}
    for rel in gh.paginate(f"/repos/{repo}/releases", max_pages=MAX_RELEASE_PAGES):
        tag = rel.get("tag_name")
        if not tag or rel.get("draft"):
            continue
        for asset in rel.get("assets", []):
            if asset["name"] == f"{tag}.xml.zst":
                found[tag] = {
                    "url": rel.get("html_url", ""),
                    "download_url": asset.get("browser_download_url", ""),
                    "bytes_compressed": asset.get("size", 0),
                    "published_at": rel.get("published_at", ""),
                }
                break
    return found


def build_rows(policy: dict, releases: dict[str, dict]) -> list[dict]:
    rows = []
    for language in policy["targets"]["languages"]:
        path = lockfile_path(language)
        if not path.exists():
            continue
        lock = read_lockfile(language, path)
        for rank, sysrec in enumerate(lock.systems, start=1):
            for srcml_version in policy["srcml"]["versions"]:
                tag = release_tag(language, sysrec.name, sysrec.version, srcml_version)
                rel = releases.get(tag)
                rows.append(
                    {
                        "language": language,
                        "language_display": LANGUAGES[language][2],
                        "rank": rank,
                        "system": sysrec.name,
                        "version": sysrec.version,
                        "version_kind": sysrec.version_kind,
                        "commit": sysrec.commit,
                        "license": sysrec.license,
                        "srcml_version": srcml_version,
                        "tag": tag,
                        "published": bool(rel),
                        **(rel or {}),
                    }
                )
    return rows


def render_markdown(rows: list[dict], repo: str) -> str:
    published = [r for r in rows if r["published"]]
    total_bytes = sum(r.get("bytes_compressed", 0) for r in published)

    out = [
        "# Archive index",
        "",
        "<!-- GENERATED by scripts/render_index.py — do not hand-edit. -->",
        "",
        f"**{len(published)}** of **{len(rows)}** archives published, "
        f"{human_bytes(total_bytes) if total_bytes else '0 B'} total.",
        "",
    ]

    by_language: dict[str, list[dict]] = {}
    for row in rows:
        by_language.setdefault(row["language"], []).append(row)

    for language, group in by_language.items():
        done = sum(1 for r in group if r["published"])
        out += [
            f"## {group[0]['language_display']}",
            "",
            f"{done}/{len(group)} published.",
            "",
            "| language | system | version | srcml version | size | archive |",
            "|---|---|---|---|---|---|",
        ]
        for r in group:
            system_link = f"[`{r['system']}`](https://github.com/{r['system']})"
            version = f"`{r['version']}`"
            if r["version_kind"] != "release":
                version += f" <sup>{r['version_kind']}</sup>"
            if r["published"]:
                size = human_bytes(r.get("bytes_compressed", 0))
                link = f"[download]({r.get('download_url','')})"
            else:
                size, link = "—", "_pending_"
            out.append(
                f"| {r['language_display']} | {system_link} | {version} "
                f"| `{r['srcml_version']}` | {size} | {link} |"
            )
        out.append("")

    out += [
        "---",
        "",
        "Each archive is a zstd-compressed srcML XML archive. To use one:",
        "",
        "```sh",
        "gh release download <tag> --repo " + repo + " --pattern '*.xml.zst'",
        "zstd -d <tag>.xml.zst",
        "```",
        "",
        "Every release also carries a `.manifest.json` recording the exact commit, "
        "srcml flags, sha256, and per-language unit counts.",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", ""))
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "INDEX.md")
    ap.add_argument("--json", type=Path, default=REPO_ROOT / "index.json")
    ap.add_argument("--token")
    args = ap.parse_args()

    if not args.repo:
        ap.error("--repo is required outside Actions (no $GITHUB_REPOSITORY)")

    policy = load_policy()
    gh = GitHub(token=args.token)
    releases = collect_releases(gh, args.repo)
    rows = build_rows(policy, releases)

    args.out.write_text(render_markdown(rows, args.repo))
    args.json.write_text(json.dumps({"repo": args.repo, "archives": rows}, indent=1) + "\n")

    done = sum(1 for r in rows if r["published"])
    print(f"wrote {args.out} and {args.json}: {done}/{len(rows)} published", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
